from typing import Literal

from isaaclab.sensors import SensorBaseCfg
from isaaclab.utils import configclass

from .gelsight_sensor import GelSightSensor
from .simulation_approaches.gelsight_simulator_cfg import GelSightSimulatorCfg

"""Configuration for a Gelsight tactile sensor."""


@configclass
class GelSightSensorCfg(SensorBaseCfg):
    class_type: type = GelSightSensor

    @configclass
    class Dimensions:
        """Dimensions here are in mm (we assume that the world units are meters)"""

        width: float = 0.0
        length: float = 0.0
        height: float = 0.0

    case_dimensions: Dimensions = Dimensions()
    gelpad_dimensions: Dimensions = Dimensions()

    max_indentation_depth: float = 0.0
    """The maximum indentation depth in [m].
    
    Used e.g. for normalizing height map w.r.t to possible indentation depth range.
    """

    @configclass
    class SensorCameraCfg:
        """Configs for the Camera of the GelSight sensor."""

        prim_name: str = "Camera"
        update_period: float = 0
        resolution: tuple[int, int] = (32, 24)
        data_types: list[str] = ["depth"]
        clipping_range: tuple[float, float] = (0.024, 0.028)
        update_latest_camera_pose: bool = False

        camera_pos_offset: tuple[float, float, float] = (0.0000, -0.0001, 0.0)
        """Translation of camera w.r.t to sensor frame. 
        
        Defaults to (-0.0001, 0.0008, 0.0) for the GelSight Mini. This offset places the camera in the center of the gelpad frame.
        Even very small changes can lead to relativly big differences in the indentation location.
        """

        camera_rot_offset: tuple[float, float, float, float] = (0.0, 1.0, 0.0, 0.0)
        """Quaternion rotation (w, x, y, z) w.r.t. the parent frame. Defaults to (0.0, 1.0, 0.0, 0.0)."""

        focal_length: float = 20
        """Focal length of the sensor camera (in [cm])."""

        focus_distance: float = 0.025
        """Distance from camera to focus plane (in [m])."""

        border_fraction: float = 0.15
        """Fraction of the image dimensions to crop from each border. Value clamped in [0.0, 0.49] 
        
        Behavior is the same as in the GelSightSDK (https://github.com/gelsightinc/gsrobotics/blob/321d6a22da64529138ff10237335038fd8c5189f/utilities/image_processing.py#L108)
        """

        fov_width = 0.00186  # 0.002525
        """Field of view width (in [m])."""

        fov_height = 0.00143  # 0.002075
        """Field of view height (in [m])."""

    sensor_camera_cfg: SensorCameraCfg = SensorCameraCfg()

    data_types: list[str] = ["tactile_rgb", "marker_motion", "height_map", "camera_depth", "camera_rgb"]
    """Output of the GelSight Sensor

    - height_map: Generated by the sensor camera. Shape = the camera resolution specified in the SensorCameraCfg.
    - tactile_rgb: Tactile RGB image. Shape = tactile_img_resolution specified in the OpticalSimulator class.
    - marker_motion: Initial and current positions of the gelpad markers.
        Shape (num_envs, 2, num_markers_markers, 2)
        - dim = 1: initial, current markers
        - dim = 2: marker pos (x,y) in the image (x = width, y = height)
    - camera_depth: depth image from the sensor camera
    - camera_rgb: rgb image from the sensor camera
    """

    optical_sim_cfg: GelSightSimulatorCfg = None  # freely choose what simulation class, but can also be left None
    """Cfg class of the optical simulator you want to use."""

    marker_motion_sim_cfg: GelSightSimulatorCfg = None
    """Cfg class of the marker motion simulator you want to use."""

    compute_indentation_depth_class: Literal["optical_sim", "marker_motion_sim", "default"] = "default"
    """Defines which approach is used for computing the indentation depth.

    You can use the method from your optical simulation (e.g. Taxim), or the one from your marker motion simulation (e.g. if its FEM based).
    By default the minimum value of the height map is used as indentation depth.
    """

    device: str = "cuda"
