seed: 42

network:
  actor_hidden_dims: [256, 256]
  critic_hidden_dims: [256, 256]
  initial_log_std: -3.0

memory_size: 50000

agent:
  gradient_steps: 1
  batch_size: 256
  discount_factor: 0.99
  polyak: 0.005
  learning_rate: [0.00003, 0.0001, 0.0]
  learning_rate_scheduler: null
  learning_rate_scheduler_kwargs: {}
  observation_preprocessor: null
  observation_preprocessor_kwargs: {}
  state_preprocessor: null
  state_preprocessor_kwargs: {}
  random_timesteps: 0
  learning_starts: 5000
  grad_norm_clip: 5.0
  learn_entropy: false
  initial_entropy_value: 0.0
  target_entropy: null
  rewards_shaper: null
  mixed_precision: false

  experiment:
    directory: "lab_pick_slide"
    experiment_name: "clean_residual_sac"
    write_interval: 100
    checkpoint_interval: 2500
    store_separately: false
    wandb: false
    wandb_kwargs: {}

trainer:
  timesteps: 50000
  environment_info: "log"
